#!/bin/bash

A=10
B=500
C=$((10 * $B + ($A ** 4)))

echo $C

COST_PINEAPPLE=50
COST_BANANA=4
COST_WATERMELON=23
COST_BASKET=1
TOTAL=$(($COST_PINEAPPLE + (2 * $COST_BANANA) + (3 * $COST_WATERMELON) + $COST_BASKET))
echo "Total Cost is $TOTAL"
